export type LinuxCommand = { cmd: string; description: string }
export type LinuxCategory = { category: string; commands: LinuxCommand[] }

export const LINUX_REFERENCE: LinuxCategory[] = [
  {
    category: 'Files & Directories',
    commands: [
      { cmd: 'ls -la', description: 'List all files (including hidden), long format with permissions/size/date' },
      { cmd: 'ls -lh', description: 'Long format with human-readable sizes (K/M/G instead of bytes)' },
      { cmd: 'ls -lt', description: 'Sort by modification time, newest first' },
      { cmd: 'cd -', description: 'Switch back to the previous directory' },
      { cmd: 'mkdir -p a/b/c', description: 'Create nested directories, no error if they already exist' },
      { cmd: 'cp -r src/ dst/', description: 'Copy a directory recursively' },
      { cmd: 'cp -a src/ dst/', description: 'Copy recursively, preserving permissions/timestamps/symlinks' },
      { cmd: 'mv old new', description: 'Rename or move a file/directory' },
      { cmd: 'rm -rf dir/', description: 'Delete a directory and everything in it, no confirmation — irreversible' },
      { cmd: 'ln -s target linkname', description: 'Create a symbolic link' },
      { cmd: 'find . -type f -name "*.log"', description: 'Find files by name pattern' },
      { cmd: 'find . -type d -empty', description: 'Find empty directories' },
      { cmd: 'du -sh dir/', description: "Total size of a directory, human-readable (doesn't list contents)" },
      { cmd: 'du -h --max-depth=1 dir/', description: 'Size of each immediate subdirectory' },
      { cmd: 'stat file', description: 'Detailed metadata: size, permissions, timestamps, inode' },
      { cmd: 'realpath file', description: 'Resolve a relative path (or symlink) to its absolute path' },
      { cmd: 'tree -L 2', description: 'Directory tree, 2 levels deep' },
    ],
  },
  {
    category: 'Text Processing',
    commands: [
      { cmd: 'grep -rn "pattern" .', description: 'Recursively search files for a pattern, showing line numbers' },
      { cmd: 'grep -ri "pattern" .', description: 'Same, case-insensitive' },
      { cmd: 'grep -v "pattern" file', description: 'Show lines that do NOT match' },
      { cmd: 'grep -l "pattern" *', description: 'List only filenames that contain a match' },
      { cmd: 'grep -c "pattern" file', description: 'Count matching lines instead of printing them' },
      { cmd: "sed -i 's/old/new/g' file", description: 'Replace all occurrences of old with new, in place' },
      { cmd: "sed -n '10,20p' file", description: 'Print only lines 10 through 20' },
      { cmd: "awk '{print $1}' file", description: 'Print the first whitespace-separated column of each line' },
      { cmd: "awk -F',' '{print $2}' file", description: 'Same, but split on commas instead of whitespace' },
      { cmd: 'sort file', description: 'Sort lines alphabetically' },
      { cmd: 'sort -n file', description: 'Sort numerically instead of lexicographically' },
      { cmd: 'sort -k2 -t, file', description: 'Sort by the 2nd comma-separated field' },
      { cmd: 'uniq -c', description: 'Collapse adjacent duplicate lines, prefixing each with a count (pair with sort first)' },
      { cmd: 'wc -l file', description: 'Count lines (wc -w words, wc -c bytes)' },
      { cmd: "cut -d',' -f1,3 file", description: 'Extract the 1st and 3rd comma-separated fields' },
      { cmd: 'tr "a-z" "A-Z" < file', description: 'Translate characters — here, lowercase to uppercase' },
      { cmd: 'diff -u a.txt b.txt', description: 'Unified diff between two files' },
      { cmd: 'xargs -I{} cmd {}', description: 'Run cmd once per line of input, substituting {} for the line' },
      { cmd: 'jq .', description: 'Pretty-print/query JSON on stdin (not installed everywhere by default)' },
    ],
  },
  {
    category: 'Permissions & Users',
    commands: [
      { cmd: 'chmod 755 file', description: 'Set permissions by octal (owner rwx, group/other rx)' },
      { cmd: 'chmod +x script.sh', description: 'Add execute permission without touching other bits' },
      { cmd: 'chmod -R 644 dir/', description: 'Recursively set permissions on a whole directory tree' },
      { cmd: 'chown user:group file', description: 'Change owning user and group' },
      { cmd: 'chown -R user:group dir/', description: 'Recursively change ownership' },
      { cmd: 'chgrp group file', description: 'Change only the owning group' },
      { cmd: 'umask', description: 'Show the default permission mask applied to newly created files' },
      { cmd: 'sudo -l', description: 'List the commands you are allowed to run with sudo' },
      { cmd: 'su - username', description: "Switch to another user's login shell" },
      { cmd: 'whoami', description: 'Print the current effective username' },
      { cmd: 'id', description: 'Show current user/group IDs and group memberships' },
    ],
  },
  {
    category: 'Processes & Monitoring',
    commands: [
      { cmd: 'ps aux', description: 'List every running process, BSD-style (full detail)' },
      { cmd: 'ps aux | grep java', description: 'Find processes matching a name' },
      { cmd: 'kill -9 PID', description: 'Force-kill a process (SIGKILL) — SIGTERM (default, no -9) is usually preferred first' },
      { cmd: 'kill -15 PID', description: 'Ask a process to terminate gracefully (SIGTERM)' },
      { cmd: 'killall processname', description: 'Kill every process matching a name' },
      { cmd: 'pkill -f "pattern"', description: 'Kill processes whose full command line matches a pattern' },
      { cmd: 'top', description: 'Live-updating process/resource monitor' },
      { cmd: 'htop', description: 'Nicer interactive version of top (often needs installing separately)' },
      { cmd: 'free -h', description: 'Memory usage, human-readable' },
      { cmd: 'uptime', description: 'How long the system has been up, plus load averages' },
      { cmd: 'nice -n 10 cmd', description: 'Run a command with lower CPU priority' },
      { cmd: 'renice -n 10 -p PID', description: 'Change the priority of an already-running process' },
      { cmd: 'nohup cmd &', description: 'Run a command in the background, immune to hangup when you log out' },
      { cmd: 'jobs', description: 'List background jobs started in the current shell' },
      { cmd: 'fg %1 / bg %1', description: 'Bring job 1 to the foreground / resume it in the background' },
      { cmd: 'lsof -i :8080', description: 'Find which process is listening on port 8080' },
      { cmd: 'strace -p PID', description: 'Trace the system calls a running process is making' },
    ],
  },
  {
    category: 'Networking',
    commands: [
      { cmd: 'curl -sS https://example.com', description: 'Fetch a URL, silent but still show errors' },
      { cmd: 'wget https://example.com/file', description: 'Download a file to disk' },
      { cmd: 'ssh user@host', description: 'Open a remote shell' },
      { cmd: 'ssh -i key.pem user@host', description: 'Connect using a specific private key' },
      { cmd: 'scp file user@host:/path/', description: 'Copy a file to a remote host over SSH' },
      { cmd: 'scp -r dir/ user@host:/path/', description: 'Copy a whole directory recursively' },
      { cmd: 'rsync -avz src/ user@host:/dst/', description: 'Efficiently sync files, compressed, preserving attributes' },
      { cmd: 'ping -c 4 host', description: 'Send 4 ICMP pings (omit -c on Linux and it runs forever)' },
      { cmd: 'dig example.com', description: 'DNS lookup with full detail' },
      { cmd: 'nslookup example.com', description: 'Simpler DNS lookup' },
      { cmd: 'ss -tulpn', description: 'List listening TCP/UDP sockets with owning process (modern replacement for netstat)' },
      { cmd: 'ip addr', description: "Show this machine's network interfaces and IPs" },
      { cmd: 'traceroute host', description: 'Show the network hops to reach a host' },
      { cmd: 'nc -zv host port', description: 'Check whether a TCP port is open on a host' },
      { cmd: 'nmap -p 1-1000 host', description: 'Scan a range of ports on a host' },
    ],
  },
  {
    category: 'Archives & Compression',
    commands: [
      { cmd: 'tar -czvf archive.tar.gz dir/', description: 'Create a gzip-compressed tarball' },
      { cmd: 'tar -xzvf archive.tar.gz', description: 'Extract a gzip-compressed tarball' },
      { cmd: 'tar -tzvf archive.tar.gz', description: 'List contents without extracting' },
      { cmd: 'tar -xzvf archive.tar.gz -C /dst', description: 'Extract into a specific directory' },
      { cmd: 'zip -r archive.zip dir/', description: 'Create a zip archive from a directory' },
      { cmd: 'unzip archive.zip', description: 'Extract a zip archive' },
      { cmd: 'unzip -l archive.zip', description: 'List zip contents without extracting' },
      { cmd: 'gzip file', description: 'Compress a file in place, producing file.gz' },
      { cmd: 'gunzip file.gz', description: 'Decompress a .gz file in place' },
    ],
  },
  {
    category: 'Packages & Services',
    commands: [
      { cmd: 'apt update && apt install pkg', description: 'Debian/Ubuntu: refresh package index, then install' },
      { cmd: 'apt list --installed', description: 'List installed packages (Debian/Ubuntu)' },
      { cmd: 'dnf install pkg', description: 'Fedora/RHEL package install' },
      { cmd: 'systemctl status svc', description: 'Show whether a systemd service is running and its recent logs' },
      { cmd: 'systemctl start svc / stop svc', description: 'Start or stop a systemd service now' },
      { cmd: 'systemctl enable svc', description: 'Make a service start automatically on boot' },
      { cmd: 'systemctl restart svc', description: 'Restart a service' },
      { cmd: 'journalctl -u svc -f', description: 'Follow live logs for a specific systemd unit' },
      { cmd: 'crontab -e', description: 'Edit the current user\'s scheduled cron jobs' },
      { cmd: 'crontab -l', description: 'List the current user\'s cron jobs' },
    ],
  },
  {
    category: 'Docker',
    commands: [
      { cmd: 'docker ps', description: 'List running containers' },
      { cmd: 'docker ps -a', description: 'List all containers, including stopped ones' },
      { cmd: 'docker logs -f container', description: 'Follow live logs from a container' },
      { cmd: 'docker exec -it container sh', description: 'Open an interactive shell inside a running container' },
      { cmd: 'docker build -t name .', description: 'Build an image from a Dockerfile in the current directory' },
      { cmd: 'docker run -p 8080:80 image', description: 'Run a container, mapping host port 8080 to container port 80' },
      { cmd: 'docker stop container', description: 'Gracefully stop a running container' },
      { cmd: 'docker rm container', description: 'Remove a stopped container' },
      { cmd: 'docker rmi image', description: 'Remove an image' },
      { cmd: 'docker compose up -d', description: 'Start all services defined in docker-compose.yml, detached' },
      { cmd: 'docker compose logs -f', description: 'Follow logs from all compose services' },
      { cmd: 'docker system prune -a', description: 'Remove all unused containers/images/networks — frees disk space' },
    ],
  },
]

export type LinuxRecipe = { question: string; command: string; note?: string }

export const LINUX_RECIPES: LinuxRecipe[] = [
  { question: 'Find and delete files older than 30 days', command: 'find . -type f -mtime +30 -delete', note: 'Run without -delete first to see what would be removed.' },
  { question: 'Find which process is using port 8080', command: 'lsof -i :8080', note: 'Or: ss -tulpn | grep 8080' },
  { question: 'Kill whatever is listening on port 8080', command: 'kill -9 $(lsof -t -i :8080)' },
  { question: 'Recursively change ownership of a directory', command: 'sudo chown -R user:group dir/' },
  { question: 'Watch a log file for new lines in real time', command: 'tail -f /var/log/app.log' },
  { question: 'Watch a log file for errors only, in real time', command: 'tail -f app.log | grep --line-buffered -i error' },
  { question: 'Find the 10 largest files under the current directory', command: 'find . -type f -exec du -h {} + | sort -rh | head -10' },
  { question: 'Find the 10 largest directories one level down', command: 'du -h --max-depth=1 . | sort -rh | head -10' },
  { question: 'See which process is using the most memory', command: 'ps aux --sort=-%mem | head -10' },
  { question: 'See which process is using the most CPU', command: 'ps aux --sort=-%cpu | head -10' },
  { question: 'Batch-rename all .txt files to .bak', command: 'for f in *.txt; do mv "$f" "${f%.txt}.bak"; done' },
  { question: 'Search recursively for a string, excluding node_modules', command: 'grep -rn "pattern" . --exclude-dir=node_modules' },
  { question: 'Run a job every 5 minutes with cron', command: '*/5 * * * * /path/to/script.sh', note: 'Add via crontab -e. Redirect output: >> /var/log/script.log 2>&1' },
  { question: 'Copy files to a remote server, preserving permissions', command: 'rsync -avz -e ssh src/ user@host:/dst/' },
  { question: 'Check if a port is reachable on a remote host', command: 'nc -zv host 443' },
  { question: 'Kill all processes matching a name', command: 'pkill -f processname' },
  { question: 'Extract one specific file from a tar archive', command: 'tar -xzvf archive.tar.gz path/inside/archive/file.txt' },
  { question: 'Run a long command that survives logging out', command: 'nohup long-running-command &', note: 'Or use tmux/screen for something you want to reattach to later.' },
  { question: 'Find broken symlinks in a directory', command: 'find . -xtype l' },
  { question: 'Count lines, words, and characters in a file', command: 'wc -l -w -c file' },
  { question: 'Merge multiple files into one', command: 'cat part1.txt part2.txt part3.txt > combined.txt' },
  { question: 'Find files modified in the last hour', command: 'find . -type f -mmin -60' },
  { question: 'Replace a string across many files at once', command: "grep -rl 'old' . | xargs sed -i 's/old/new/g'", note: 'On macOS/BSD sed, add \'\' after -i.' },
  { question: 'See real-time disk/network/CPU activity in one view', command: 'top', note: 'Or dstat / htop if installed.' },
  { question: 'Check free disk space on every mounted filesystem', command: 'df -h' },
  { question: 'Find out which package installed a command', command: 'dpkg -S $(which cmd)', note: 'Debian/Ubuntu. RHEL/Fedora: rpm -qf $(which cmd)' },
  { question: 'Make a script executable and run it', command: 'chmod +x script.sh && ./script.sh' },
  { question: 'Compare two directories recursively', command: 'diff -rq dir1/ dir2/' },
  { question: 'Generate a random password', command: 'openssl rand -base64 16' },
  { question: 'Check how long the system has been running', command: 'uptime' },
]

export const FLAG_REFERENCE: Record<string, LinuxCommand[]> = {
  find: [
    { cmd: '-name PATTERN', description: 'Match by filename (glob, case-sensitive)' },
    { cmd: '-iname PATTERN', description: 'Match by filename, case-insensitive' },
    { cmd: '-type f|d|l', description: 'Only files / directories / symlinks' },
    { cmd: '-mtime -N|+N', description: 'Modified less than / more than N days ago' },
    { cmd: '-mmin -N|+N', description: 'Modified less than / more than N minutes ago' },
    { cmd: '-size +N[kMG]', description: 'Larger than N (k=KB, M=MB, G=GB)' },
    { cmd: '-maxdepth N', description: "Don't descend more than N levels" },
    { cmd: '-empty', description: 'Match empty files or directories' },
    { cmd: '-xtype l', description: 'Match broken symlinks (link exists, target does not)' },
    { cmd: '-exec CMD {} \\;', description: 'Run CMD on each match ({} = the path)' },
    { cmd: '-exec CMD {} +', description: 'Same, but batches matches into fewer CMD invocations (faster)' },
    { cmd: '-delete', description: 'Delete matches (put last, after all filters)' },
  ],
  grep: [
    { cmd: '-r', description: 'Recurse into directories' },
    { cmd: '-n', description: 'Show line numbers' },
    { cmd: '-i', description: 'Case-insensitive' },
    { cmd: '-v', description: 'Invert match — show non-matching lines' },
    { cmd: '-l', description: 'Print only matching filenames, not the lines' },
    { cmd: '-c', description: 'Print a count of matching lines per file' },
    { cmd: '-E', description: 'Extended regex (so you can use +, ?, | without escaping)' },
    { cmd: '-A N / -B N', description: 'Show N lines of context after / before each match' },
    { cmd: '--exclude-dir=DIR', description: 'Skip a directory (e.g. node_modules)' },
  ],
  sed: [
    { cmd: "-i 's/a/b/g'", description: 'Edit in place, replacing every occurrence of a with b' },
    { cmd: "-n '10,20p'", description: "Suppress default output, print only lines 10-20 ('n' + 'p' pattern)" },
    { cmd: '-e SCRIPT', description: 'Add another script/expression (repeatable)' },
    { cmd: '-E', description: 'Extended regex syntax' },
  ],
  awk: [
    { cmd: "'{print $1}'", description: 'Print the first whitespace-separated field' },
    { cmd: "-F','", description: 'Use comma as the field separator instead of whitespace' },
    { cmd: "'NR==2'", description: 'Only process line number 2' },
    { cmd: "'{sum+=$1} END{print sum}'", description: 'Sum a column and print the total at the end' },
  ],
  chmod: [
    { cmd: '-R', description: 'Recurse into subdirectories' },
    { cmd: '+x', description: 'Add execute permission' },
    { cmd: '-w', description: 'Remove write permission' },
    { cmd: '755', description: 'Octal shorthand: owner rwx, group/other r-x' },
    { cmd: '644', description: 'Octal shorthand: owner rw-, group/other r--' },
  ],
  chown: [
    { cmd: '-R', description: 'Recurse into subdirectories' },
    { cmd: 'user:group', description: 'Set both owning user and group' },
    { cmd: 'user:', description: 'Set only the user, leave group unchanged' },
    { cmd: ':group', description: 'Set only the group, leave user unchanged' },
  ],
  ps: [
    { cmd: 'aux', description: 'Every process, BSD syntax, full detail' },
    { cmd: '-ef', description: 'Every process, System V syntax (similar info, different columns)' },
    { cmd: '--sort=-%cpu', description: 'Sort by CPU usage, descending' },
    { cmd: '--sort=-%mem', description: 'Sort by memory usage, descending' },
  ],
  kill: [
    { cmd: '-9', description: 'SIGKILL — force-terminate immediately, no cleanup' },
    { cmd: '-15', description: 'SIGTERM — ask the process to shut down gracefully (default)' },
    { cmd: '-l', description: 'List all signal names' },
  ],
  du: [
    { cmd: '-s', description: 'Summarize — total only, not every file' },
    { cmd: '-h', description: 'Human-readable sizes' },
    { cmd: '--max-depth=N', description: 'Only show totals down to N levels deep' },
  ],
  df: [
    { cmd: '-h', description: 'Human-readable sizes' },
    { cmd: '-T', description: 'Show filesystem type per mount' },
  ],
  tar: [
    { cmd: '-c', description: 'Create an archive' },
    { cmd: '-x', description: 'Extract an archive' },
    { cmd: '-t', description: 'List contents without extracting' },
    { cmd: '-z', description: 'gzip compression (.tar.gz)' },
    { cmd: '-j', description: 'bzip2 compression (.tar.bz2)' },
    { cmd: '-v', description: 'Verbose — print each file' },
    { cmd: '-f FILE', description: 'Archive filename (almost always needed, goes last)' },
    { cmd: '-C DIR', description: 'Change to DIR before acting (extract elsewhere)' },
  ],
  curl: [
    { cmd: '-X METHOD', description: 'HTTP method (GET/POST/PUT/DELETE...)' },
    { cmd: '-H "Header: value"', description: 'Add a request header (repeatable)' },
    { cmd: '-d DATA', description: 'Send data as request body (implies POST)' },
    { cmd: '-o FILE', description: 'Write response body to FILE' },
    { cmd: '-L', description: 'Follow redirects' },
    { cmd: '-i', description: 'Include response headers in output' },
    { cmd: '-s', description: 'Silent — no progress meter' },
    { cmd: '-v', description: 'Verbose — show the full request/response' },
    { cmd: '-u user:pass', description: 'Basic auth credentials' },
    { cmd: '-k', description: 'Skip TLS certificate verification (dev only!)' },
  ],
  ssh: [
    { cmd: '-L localPort:host:remotePort', description: 'Local port forward (tunnel a remote service to your machine)' },
    { cmd: '-R remotePort:host:localPort', description: 'Remote port forward (expose your local service to the remote side)' },
    { cmd: '-N', description: "Don't run a remote command — just forward" },
    { cmd: '-i FILE', description: 'Identity (private key) file' },
    { cmd: '-p PORT', description: 'Non-default SSH port' },
  ],
  scp: [
    { cmd: '-r', description: 'Recurse — copy a whole directory' },
    { cmd: '-P PORT', description: 'Non-default SSH port (capital P, unlike ssh)' },
    { cmd: '-i FILE', description: 'Identity (private key) file' },
  ],
  rsync: [
    { cmd: '-a', description: 'Archive mode (preserves permissions, times, symlinks — almost always wanted)' },
    { cmd: '-v', description: 'Verbose' },
    { cmd: '-z', description: 'Compress during transfer' },
    { cmd: '-n', description: 'Dry run — show what would happen, change nothing' },
    { cmd: '--delete', description: 'Delete files in destination that no longer exist in source' },
    { cmd: '-e "ssh -p PORT"', description: 'Use a non-default SSH port' },
  ],
  netstat: [
    { cmd: '-t', description: 'TCP sockets' },
    { cmd: '-u', description: 'UDP sockets' },
    { cmd: '-l', description: 'Listening sockets only' },
    { cmd: '-n', description: "Numeric addresses (don't resolve DNS)" },
    { cmd: '-p', description: 'Show the owning process (needs root for others\' processes)' },
  ],
  ss: [
    { cmd: '-t', description: 'TCP sockets' },
    { cmd: '-u', description: 'UDP sockets' },
    { cmd: '-l', description: 'Listening sockets only' },
    { cmd: '-n', description: "Numeric addresses (don't resolve DNS)" },
    { cmd: '-p', description: 'Show the owning process' },
  ],
  lsof: [
    { cmd: '-i :PORT', description: 'Show what has a given port open' },
    { cmd: '-p PID', description: 'Show files/sockets opened by a specific process' },
    { cmd: '-u USER', description: "Show files/sockets opened by a specific user's processes" },
  ],
  journalctl: [
    { cmd: '-u UNIT', description: 'Only this systemd unit' },
    { cmd: '-f', description: 'Follow (like tail -f)' },
    { cmd: '-n N', description: 'Show last N lines' },
    { cmd: '--since "TIME"', description: 'Only entries after TIME' },
    { cmd: '-p PRIORITY', description: 'Minimum priority (err, warning, info...)' },
    { cmd: '-r', description: 'Reverse — newest first' },
  ],
  systemctl: [
    { cmd: 'status UNIT', description: 'Show whether a unit is active and recent log lines' },
    { cmd: 'start|stop|restart UNIT', description: 'Control a unit right now' },
    { cmd: 'enable|disable UNIT', description: 'Control whether a unit starts automatically on boot' },
    { cmd: 'daemon-reload', description: 'Reload unit files after editing one' },
  ],
  docker: [
    { cmd: 'ps -a', description: 'List all containers, including stopped ones' },
    { cmd: 'logs -f CONTAINER', description: 'Follow live logs from a container' },
    { cmd: 'exec -it CONTAINER sh', description: 'Open an interactive shell in a running container' },
    { cmd: 'build -t NAME .', description: 'Build an image tagged NAME from the current directory' },
    { cmd: 'run -p HOST:CONTAINER IMAGE', description: 'Run a container, mapping a host port to a container port' },
  ],
}

export function explainCommand(input: string): LinuxCommand[] {
  const tokens = input.trim().split(/\s+/)
  const base = tokens[0]?.replace(/^.*\//, '')
  const docs = FLAG_REFERENCE[base]
  if (!docs) return []
  const matched: LinuxCommand[] = []
  for (const token of tokens.slice(1)) {
    const flagKey = token.replace(/^(-[a-zA-Z-]+).*/, '$1')
    const doc = docs.find((d) => d.cmd.startsWith(flagKey) && flagKey.length > 1)
    if (doc && !matched.includes(doc)) matched.push(doc)
  }
  return matched
}

export function searchLinuxReference(query: string): LinuxCategory[] {
  if (!query.trim()) return LINUX_REFERENCE
  const q = query.toLowerCase()
  return LINUX_REFERENCE
    .map((cat) => ({
      category: cat.category,
      commands: cat.commands.filter((c) => c.cmd.toLowerCase().includes(q) || c.description.toLowerCase().includes(q)),
    }))
    .filter((cat) => cat.commands.length > 0)
}
